vich_uploader:
    db_driver: orm
  
    mappings:
        video_images:
            uri_prefix: '%app.path.video_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.video_images%'
            namer: 'Vich\UploaderBundle\Naming\UniqidNamer'
            delete_on_remove: true
            delete_on_update: true         
